Repository sonata-project/SonataCacheBundle, pull requests merged in 2021-12, with the labels that each got.

#403 fix(command): remove null arg to match code
  src/Resources/config/cache.xml
Labels: patch

#385 Add Symfony 6 support
  .github/workflows/test.yaml
  composer.json
Labels: minor

#402 Mark as abandoned
  composer.json
Labels: pedantic
